name: Build App
 
on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set Version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${{ github.ref }})

    - name: Update Assembly version
      shell: powershell
      run: (Get-Content Directory.Build.Targets).replace('1.0.0', '${{ github.ref }}').replace("refs/tags/v", "") | Set-Content Directory.Build.Targets

    - name: Restore the application
      run: dotnet restore

    - name: Build the application
      run: |
        dotnet build LostArkLogger\LostArkLogger.csproj -c Release --no-restore
        dotnet publish LostArkLogger\LostArkLogger.csproj -c Release -o publish -r win10-x64 --no-self-contained

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AccessoryOptimizer.zip
        path: publish

    - name: Pack Publish Files
      run: Compress-Archive -Path publish/* -DestinationPath AccessoryOptimizer.zip

    - name: Add to releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: AccessoryOptimizer.zip